sql
-- =============================================
-- Regions Data Insertion Script
-- Generated by SMG (Synthetic Data Management Generator)
-- =============================================
truncate table regions;
