sql
-- =============================================
-- Regions Data Insertion Script
-- Generated by SMG (Synthetic Data Management Generator)
-- =============================================

-- Inserting region records with consistent formatting
INSERT INTO regions (region_id, region_name) VALUES
    (10, 'Europe'),
    (20, 'Americas'),
    (30, 'Asia'),
    (40, 'Oceania'),
    (50, 'Africa');
